In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
epw_file = 'BRA_BA_Salvador-Magalhaes.Intl.AP.832480_TRY.1961.epw'
print(epw_file)
(epw_filename, epw_ext) = os.path.splitext(epw_file)
print(epw_filename)
epw_modifiername = '_modified_mkb'

BRA_BA_Salvador-Magalhaes.Intl.AP.832480_TRY.1961.epw
BRA_BA_Salvador-Magalhaes.Intl.AP.832480_TRY.1961

In [3]:
log_file = 'BRA_Salvador-Magalhaes Intl AP_radiation_log.log'
print(log_file)

BRA_Salvador-Magalhaes Intl AP_radiation_log.log

In [4]:
epw_header0 = pd.read_csv(epw_file, nrows=1,header=None,low_memory=False)
epw_header1 = pd.read_csv(epw_file,skiprows=[0], nrows=1, header=None, low_memory=False)
epw_header2 = pd.read_csv(epw_file,skiprows=[0,1], nrows=1, header=None, low_memory=False)
epw_header3 = pd.read_csv(epw_file,skiprows=[0,1,2], nrows=1, header=None, low_memory=False)
epw_header4 = pd.read_csv(epw_file,skiprows=[0,1,2,3], nrows=1, header=None, low_memory=False)
epw_header5 = pd.read_csv(epw_file,skiprows=[0,1,2,3,4], nrows=1, header=None, low_memory=False)
epw_header6 = pd.read_csv(epw_file,skiprows=[0,1,2,3,4,5], nrows=1, header=None, low_memory=False)
epw_header7 = pd.read_csv(epw_file,skiprows=[0,1,2,3,4,5,6], nrows=1, header=None, low_memory=False)

print(epw_header0)
print(epw_header1)
print(epw_header2)
print(epw_header3)
print(epw_header4)
print(epw_header5)
print(epw_header6)
print(epw_header7)

          0                           1   2    3           4       5     6  \
0  LOCATION  Salvador-Magalhaes Intl AP  BA  BRA  TRY Brazil  832480 -12.9

       7    8     9
0 -38.33 -3.0  13.0
                  0   1                                                  2   \
0  DESIGN CONDITIONS   1  2017 ASHRAE Handbook -- Fundamentals - Chapter...

   3        4   5     6     7     8     9   ...   60    61    62    63    64  \
0 NaN  Heating   8  20.8  21.2  16.5  11.8  ...  2.1  17.8  35.2  17.1  36.5

     65    66    67    68    69
0  16.3  37.7  15.3  39.2  17.2

[1 rows x 70 columns]
                        0   1                                         2   \
0  TYPICAL/EXTREME PERIODS   3  No Dry Season - Week Near Average Annual

        3      4      5                                     6        7     8   \
0  Typical  10/ 8  10/14  No Dry Season - Week Near Annual Max  Extreme  3/19

     9                                     10       11    12    13
0  3/25  No Dry Season - Week Near Annual Min  Extreme  7/16  7/22
                    0   1    2   3   4   5      6     7      8      9   ...  \
0  GROUND TEMPERATURES   3  0.5 NaN NaN NaN  26.26  26.8  26.93  26.78  ...

      40     41     42     43     44     45     46     47     48     49
0  26.06  26.13  25.97  25.63  25.21  24.81  24.55  24.49  24.66  24.99

[1 rows x 50 columns]
                           0   1  2  3  4
0  HOLIDAYS/DAYLIGHT SAVINGS  No  0  0  0
            0                                                  1
0  COMMENTS 1  Laborat�rio de Efici�ncia Energ�tica em Edific...
            0                                                  1
0  COMMENTS 2  Downloaded from Climate.Onebuilding.org -- Gro...
              0  1  2     3       4      5      6
0  DATA PERIODS  1  1  Data  Sunday   1/ 1  12/31

In [5]:
df = pd.read_csv(epw_file, skiprows=[0,1,2,3,4,5,6,7], header=None, low_memory=False)

In [6]:
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,2005,1,1,1,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.7,82,101200,...,999,9,999999999,84,0.164,0,88,0.2,0.0,0.0
1,2005,1,1,2,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.0,22.0,85,101200,...,999,9,999999999,86,0.164,0,88,0.2,0.0,0.0
2,2005,1,1,3,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.0,22.6,88,101200,...,999,9,999999999,92,0.164,0,88,0.2,0.0,0.0
3,2005,1,1,4,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,24.8,22.5,89,101200,...,999,9,999999999,91,0.164,0,88,0.2,0.0,0.0
4,2005,1,1,5,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,24.5,22.2,89,101200,...,999,9,999999999,88,0.164,0,88,0.2,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2005,12,31,20,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.6,81,101100,...,999,9,999999999,83,0.164,0,88,0.2,0.0,0.0
8756,2005,12,31,21,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.2,21.7,82,101200,...,999,9,999999999,84,0.164,0,88,0.2,0.0,0.0
8757,2005,12,31,22,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,22.2,84,101300,...,999,9,999999999,88,0.164,0,88,0.2,0.0,0.0
8758,2005,12,31,23,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.7,82,101300,...,999,9,999999999,84,0.164,0,88,0.2,0.0,0.0
8759,2005,12,31,24,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.3,22.5,86,101300,...,999,9,999999999,91,0.164,0,88,0.2,0.0,0.0

In [7]:
log = pd.read_csv(log_file, skiprows=[0,1,2,3,4], header=None, skip_blank_lines=False)
blank_log = log.loc[log.isnull().all(1)]

if len(blank_log) > 0:
    first_blank_index = blank_log.index[0]
    log = log[:first_blank_index]

In [8]:
log = log.astype(int)

In [9]:
df[35]=df[1].map(str)+'_'+df[2].map(str)+'_'+df[3].map(str)
df

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,2005,1,1,1,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.7,82,101200,...,9,999999999,84,0.164,0,88,0.2,0.0,0.0,1_1_1
1,2005,1,1,2,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.0,22.0,85,101200,...,9,999999999,86,0.164,0,88,0.2,0.0,0.0,1_1_2
2,2005,1,1,3,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.0,22.6,88,101200,...,9,999999999,92,0.164,0,88,0.2,0.0,0.0,1_1_3
3,2005,1,1,4,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,24.8,22.5,89,101200,...,9,999999999,91,0.164,0,88,0.2,0.0,0.0,1_1_4
4,2005,1,1,5,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,24.5,22.2,89,101200,...,9,999999999,88,0.164,0,88,0.2,0.0,0.0,1_1_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2005,12,31,20,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.6,81,101100,...,9,999999999,83,0.164,0,88,0.2,0.0,0.0,12_31_20
8756,2005,12,31,21,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.2,21.7,82,101200,...,9,999999999,84,0.164,0,88,0.2,0.0,0.0,12_31_21
8757,2005,12,31,22,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,22.2,84,101300,...,9,999999999,88,0.164,0,88,0.2,0.0,0.0,12_31_22
8758,2005,12,31,23,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.7,82,101300,...,9,999999999,84,0.164,0,88,0.2,0.0,0.0,12_31_23
8759,2005,12,31,24,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.3,22.5,86,101300,...,9,999999999,91,0.164,0,88,0.2,0.0,0.0,12_31_24

In [10]:
log[5]=log[0].map(str)+'_'+log[1].map(str)+'_'+log[2].map(str)

In [11]:
log

      0   1   2    3    4         5
0     1   1  18  158  280    1_1_18
1     1   1  19    0   51    1_1_19
2     1   2  17  486  513    1_2_17
3     1   2  18  160  264    1_2_18
4     1   2  19    0   49    1_2_19
..   ..  ..  ..  ...  ...       ...
811  12  30  17  478  525  12_30_17
812  12  30  18  153  249  12_30_18
813  12  30  19    0   57  12_30_19
814  12  31  18  155  173  12_31_18
815  12  31  19    0   31  12_31_19

[816 rows x 6 columns]

In [12]:
df_index=df.loc[df[35]==log[5][0]].index
df_index[0]

17

In [13]:
df.iat[((df.loc[df[35]==log[5][0]]).index)[0],13] = log[3][0]

In [14]:
for i in range (log.shape[0]):
    df_index=df.loc[df[35]==log[5][i]].index
    df.iat[((df.loc[df[35]==log[5][i]]).index)[0],13] = log[3][i]

17
18
40
41
42
66
89
90
113
114
137
138
160
161
162
184
185
186
208
209
210
232
233
234
257
258
282
305
306
329
330
354
377
378
402
424
425
426
449
450
472
473
474
498
522
545
546
568
569
570
593
594
616
617
618
640
641
642
664
665
666
688
689
690
713
714
737
738
761
762
785
786
809
810
834
857
858
882
905
906
929
930
953
954
977
978
1001
1002
1025
1026
1049
1050
1073
1074
1097
1098
1121
1122
1145
1146
1169
1170
1193
1194
1217
1218
1241
1242
1265
1266
1289
1290
1313
1314
1337
1338
1361
1362
1385
1386
1409
1410
1433
1434
1457
1458
1480
1481
1482
1505
1506
1528
1529
1530
1552
1553
1554
1576
1577
1578
1601
1602
1624
1625
1626
1648
1649
1650
1673
1674
1697
1698
1720
1721
1722
1745
1746
1769
1770
1793
1794
1816
1817
1818
1840
1841
1842
1865
1866
1889
1890
1913
1914
1936
1937
1938
1960
1961
1962
1985
1986
2009
2010
2033
2034
2057
2058
2081
2082
2105
2106
2129
2130
2153
2154
2177
2178
2201
2202
2225
2226
2247
2248
2249
2250
2271
2272
2273
2274
2296
2297
2298
2320
2321
2322
2345
2346
2368
2369
2370
2392
2393
2394
2416
2417
2418
2441
2442
2464
2465
2466
2489
2490
2512
2513
2514
2536
2537
2538
2560
2561
2584
2585
2608
2609
2631
2632
2633
2656
2657
2681
2705
2728
2729
2753
2777
2800
2801
2825
2848
2849
2871
2872
2873
2896
2897
2921
2945
2969
2992
2993
3016
3017
3041
3064
3065
3088
3089
3112
3113
3136
3137
3160
3161
3184
3185
3208
3209
3232
3233
3256
3257
3280
3281
3304
3305
3328
3329
3353
3377
3401
3425
3448
3449
3473
3497
3521
3545
3569
3593
3617
3640
3641
3664
3665
3689
3713
3736
3737
3760
3761
3785
3808
3809
3832
3833
3857
3881
3904
3905
3928
3929
3952
3953
3977
4001
4025
4048
4049
4073
4097
4120
4121
4145
4169
4193
4217
4240
4241
4265
4289
4312
4313
4337
4361
4383
4384
4385
4408
4409
4433
4455
4456
4457
4480
4481
4503
4504
4505
4529
4551
4552
4553
4577
4601
4624
4625
4647
4648
4649
4673
4697
4721
4745
4767
4768
4769
4792
4793
4817
4840
4841
4863
4864
4865
4889
4913
4937
4959
4960
4961
4985
5008
5009
5033
5055
5056
5057
5080
5081
5104
5105
5129
5153
5177
5200
5201
5224
5225
5226
5249
5250
5272
5273
5274
5297
5298
5321
5322
5345
5346
5369
5370
5393
5394
5416
5417
5418
5441
5442
5464
5465
5466
5488
5489
5490
5512
5513
5514
5537
5538
5561
5562
5584
5585
5586
5608
5609
5610
5633
5634
5657
5658
5680
5681
5682
5704
5705
5706
5729
5730
5752
5753
5754
5777
5778
5801
5802
5824
5825
5826
5848
5849
5850
5873
5874
5896
5897
5898
5920
5921
5922
5945
5946
5968
5969
5970
5992
5993
5994
6017
6018
6040
6041
6042
6064
6065
6066
6088
6089
6090
6112
6113
6114
6136
6137
6138
6160
6161
6162
6184
6185
6186
6209
6210
6232
6233
6234
6256
6257
6258
6280
6281
6282
6304
6305
6306
6328
6329
6330
6352
6353
6354
6376
6377
6378
6400
6401
6402
6424
6425
6426
6448
6449
6450
6472
6473
6474
6496
6497
6498
6520
6521
6522
6544
6545
6546
6568
6569
6570
6593
6594
6615
6616
6617
6618
6641
6642
6665
6666
6689
6690
6711
6712
6713
6714
6735
6736
6737
6738
6760
6761
6762
6785
6786
6809
6810
6831
6832
6833
6834
6857
6858
6881
6882
6903
6904
6905
6906
6929
6930
6952
6953
6954
6977
6978
7000
7001
7002
7025
7026
7048
7049
7050
7071
7072
7073
7074
7096
7097
7098
7120
7121
7122
7144
7145
7146
7168
7169
7170
7192
7193
7194
7216
7217
7218
7239
7240
7241
7242
7265
7266
7289
7290
7312
7313
7314
7336
7337
7338
7360
7361
7362
7384
7385
7386
7409
7410
7433
7434
7456
7457
7458
7481
7482
7505
7506
7528
7529
7530
7552
7553
7554
7577
7578
7601
7602
7624
7625
7626
7648
7649
7650
7672
7673
7674
7696
7697
7698
7720
7721
7722
7745
7746
7768
7769
7770
7792
7793
7794
7816
7817
7818
7841
7842
7865
7866
7889
7890
7913
7914
7936
7937
7938
7960
7961
7962
7984
7985
7986
8008
8009
8010
8033
8034
8054
8055
8056
8057
8058
8078
8079
8080
8081
8082
8102
8103
8104
8105
8106
8126
8127
8128
8129
8130
8150
8151
8152
8153
8154
8177
8178
8201
8202
8225
8226
8249
8250
8273
8274
8297
8298
8321
8322
8345
8346
8369
8370
8393
8394
8415
8416
8417
8418
8441
8442
8463
8464
8465
8466
8487
8488
8489
8490
8511
8512
8513
8514
8537
8538
8561
8562
8586
8610
8634
8657
8658
8681
8682
8705
8706
8728
8729
8730
8753
8754

In [17]:
del df[35]
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,2005,1,1,1,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.7,82,101200,...,999,9,999999999,84,0.164,0,88,0.2,0.0,0.0
1,2005,1,1,2,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.0,22.0,85,101200,...,999,9,999999999,86,0.164,0,88,0.2,0.0,0.0
2,2005,1,1,3,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.0,22.6,88,101200,...,999,9,999999999,92,0.164,0,88,0.2,0.0,0.0
3,2005,1,1,4,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,24.8,22.5,89,101200,...,999,9,999999999,91,0.164,0,88,0.2,0.0,0.0
4,2005,1,1,5,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,24.5,22.2,89,101200,...,999,9,999999999,88,0.164,0,88,0.2,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2005,12,31,20,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.6,81,101100,...,999,9,999999999,83,0.164,0,88,0.2,0.0,0.0
8756,2005,12,31,21,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.2,21.7,82,101200,...,999,9,999999999,84,0.164,0,88,0.2,0.0,0.0
8757,2005,12,31,22,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,22.2,84,101300,...,999,9,999999999,88,0.164,0,88,0.2,0.0,0.0
8758,2005,12,31,23,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.4,21.7,82,101300,...,999,9,999999999,84,0.164,0,88,0.2,0.0,0.0
8759,2005,12,31,24,0,?9?9?9?9E0?9?9?9*9*9?9?9?9?9?9?9?9?9*9*9*9*9C9...,25.3,22.5,86,101300,...,999,9,999999999,91,0.164,0,88,0.2,0.0,0.0

In [16]:
epw_header0.to_csv(epw_filename+epw_modifiername+'.epw', index=False, header=False)
epw_header1.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)
epw_header2.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)
epw_header3.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)
epw_header4.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)
epw_header5.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)
epw_header6.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)
epw_header7.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)



df.to_csv(epw_filename+epw_modifiername+'.epw', index=False, mode='a', header=False)